name: iuser
description: "iuser"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Pacotes de UI e ícones
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  lucide_icons: ^0.257.0
  animated_splash_screen: ^1.3.0
  simple_circular_progress_bar: ^1.0.2
  gif: ^2.3.0

  # Pacotes multimídia
  camera: ^0.11.2
  image_picker: ^1.1.2
  photo_manager: ^3.7.1
  media_store_plus: ^0.1.3
  video_player: ^2.9.3
  video_compress: ^3.1.4
  custom_marker: ^1.0.0
  widget_to_marker: ^1.0.6
  record: ^6.0.0
  audioplayers: ^6.5.0
  just_audio: ^0.10.4
  flutter_quill: ^11.4.2
  photofilters: ^3.0.1
  deepar_flutter: ^0.0.5

  # Firebase e autenticação
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  google_sign_in: ^6.3.0

  # Localização e mapas
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  geocoding: ^4.0.0

  # Manipulação de arquivos
  file_picker: ^10.2.4
  open_filex: ^4.7.0
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^3.3.0
  ffmpeg_kit_flutter_new: ^3.2.0
  audio_waveforms: ^1.3.0


  # Permissões
  permission_handler: ^10.0.2

  # Utilitários
  get: ^4.7.2
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  intl: ^0.19.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - images/google.png
    - images/facebook.png
    - images/instagram.png
    - images/youtube.png
    - images/tiktok.png
    - images/twitter.png
    - images/logocorinverso.png
    - images/logo.svg
    - images/home_lottie.json
    - assets/map_style.json
    - assets/images/home_lottie.json
    - assets/images/peoples_lottie.json
    - assets/images/feed_lottie.json
    - assets/images/world_lottie.json
    - assets/images/world.gif
    - assets/images/location_lottie.json
    - assets/filters/
    - assets/previews/
