// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5U99_1Y2P52PTd6m5e1bf42ZLPh7KgS8',
    appId: '1:514966603347:web:146c95a4ae6ce893ae68a6',
    messagingSenderId: '514966603347',
    projectId: 'iuserprojeto',
    authDomain: 'iuserprojeto.firebaseapp.com',
    storageBucket: 'iuserprojeto.appspot.com',
    measurementId: 'G-K9CMFYP42L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYcFIfj5tqxdI9GpWbz7anygzJFuuh7-Y',
    appId: '1:514966603347:android:5f932991117699ecae68a6',
    messagingSenderId: '514966603347',
    projectId: 'iuserprojeto',
    storageBucket: 'iuserprojeto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvCOzywBCcpztxy4WMLPlciDUUObnX1k',
    appId: '1:514966603347:ios:16344a4a427da74dae68a6',
    messagingSenderId: '514966603347',
    projectId: 'iuserprojeto',
    storageBucket: 'iuserprojeto.appspot.com',
    iosBundleId: 'com.iuser.iuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApvCOzywBCcpztxy4WMLPlciDUUObnX1k',
    appId: '1:514966603347:ios:16344a4a427da74dae68a6',
    messagingSenderId: '514966603347',
    projectId: 'iuserprojeto',
    storageBucket: 'iuserprojeto.appspot.com',
    iosBundleId: 'com.iuser.iuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5U99_1Y2P52PTd6m5e1bf42ZLPh7KgS8',
    appId: '1:514966603347:web:75d421395e936108ae68a6',
    messagingSenderId: '514966603347',
    projectId: 'iuserprojeto',
    authDomain: 'iuserprojeto.firebaseapp.com',
    storageBucket: 'iuserprojeto.appspot.com',
    measurementId: 'G-5C1DEX0W4Y',
  );
}
